n = list(input("Dime una palabra:"))
a = n.count("a")
e = n.count("e")
i = n.count("i")
o = n.count("o")
u = n.count("u")
print("Tu palabra tiene {} a, {} e, {} i, {} o, {} u".format(a, e, i, o, u))
input()
